"""Canonical NOVA-RTL data contracts."""

from nova_rtl.contracts.analysis import (
    AnalysisViewContract,
    CDCInventory,
    ClockInventory,
    CriticalPathRecord,
    EvidenceGraphSnapshot,
    PowerActivityContract,
)
from nova_rtl.contracts.base import (
    ArtifactRef,
    Diagnostic,
    EvidenceRef,
    MetricSet,
    StageInputHashes,
)
from nova_rtl.contracts.execution import PreparedCommand, RawToolResult, StageResult, ToolJob
from nova_rtl.contracts.manifest import DesignContract, ProjectManifest
from nova_rtl.contracts.platform import (
    ArchiveMetadata,
    CanonicalEnvironmentEntry,
    ComponentInventoryEntry,
    DoctorCheck,
    DoctorIssue,
    DoctorReport,
    HostPlatform,
    HydrationComponentReceipt,
    InstalledComponentReceipt,
    M0SignoffReport,
    OrganizerDecisions,
    PlatformAnalysisView,
    PlatformAnalysisViews,
    PlatformArtifact,
    PlatformLock,
    PlatformLockRequest,
    PlatformSelectionPolicy,
    PlatformSmokeReport,
    RuntimeEnvironmentEntry,
    SignoffEvidenceFile,
    SmokeTimingView,
    TimingCorner,
    TimingCornerSelection,
    ToolchainReceipt,
    ToolchainSourceManifest,
    ToolExecutableSource,
    ToolFingerprint,
    ToolSource,
)
from nova_rtl.contracts.verification import (
    ConstraintBindingManifest,
    FormalModelContract,
    ProofResult,
)

__all__ = [
    "AnalysisViewContract",
    "ArchiveMetadata",
    "ArtifactRef",
    "CDCInventory",
    "CanonicalEnvironmentEntry",
    "ComponentInventoryEntry",
    "ClockInventory",
    "ConstraintBindingManifest",
    "CriticalPathRecord",
    "DoctorCheck",
    "DesignContract",
    "Diagnostic",
    "DoctorIssue",
    "DoctorReport",
    "EvidenceRef",
    "EvidenceGraphSnapshot",
    "FormalModelContract",
    "HostPlatform",
    "HydrationComponentReceipt",
    "InstalledComponentReceipt",
    "M0SignoffReport",
    "MetricSet",
    "OrganizerDecisions",
    "PlatformAnalysisView",
    "PlatformAnalysisViews",
    "PlatformArtifact",
    "PlatformLock",
    "PlatformLockRequest",
    "PlatformSelectionPolicy",
    "PlatformSmokeReport",
    "PreparedCommand",
    "ProofResult",
    "PowerActivityContract",
    "ProjectManifest",
    "RawToolResult",
    "RuntimeEnvironmentEntry",
    "SignoffEvidenceFile",
    "SmokeTimingView",
    "StageInputHashes",
    "StageResult",
    "TimingCorner",
    "TimingCornerSelection",
    "ToolExecutableSource",
    "ToolFingerprint",
    "ToolJob",
    "ToolSource",
    "ToolchainReceipt",
    "ToolchainSourceManifest",
]
